import React from "react";
import ShareStory from "@/app/components/ShareStory";

import CryptoStoryImage from "@/public/assets/images/crypto-payment.jpg";
import CBNRegulationImage from "@/public/assets/images/cbn-regulations.jpeg";
import DeliveryImage from "@/public/assets/images/delivery.jpeg";
import ListStories from "./ListStories";

type Props = {};

const stories = [
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: DeliveryImage,
    title: "Last mile delivery is not for everyone",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CryptoStoryImage,
    title: "A web3 crypto payments company that never peaked",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
  {
    image: CBNRegulationImage,
    title: "Escaping the challenging shackles of CBN regulations",
    writtenBy: "John Doe",
    createdAt: "6 hours ago",
  },
];

export default function StoriesSection({}: Props) {
  return (
    <>
      <section className="pt-5 bg-primary md:pt-10">
        <div className="px-3 space-y-6 md:px-10 md:space-y-12 lg:space-y-16 lg:px-24">
          <ListStories stories={stories} />
        </div>
        <div className="mt-10 md:mt-20 lg:mt-32">
          <ShareStory backgroundColor="primary" />
        </div>
      </section>
    </>
  );
}
